# Generated by Django 5.0.7 on 2024-08-09 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_remove_product_stock_stock_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stocks',
        ),
        migrations.AddField(
            model_name='stock',
            name='Product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock.product'),
        ),
    ]
