# Generated by Django 5.0.7 on 2024-08-09 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0005_remove_stock_stocks_stock_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='Product',
            new_name='product',
        ),
    ]
