# Generated by Django 5.0.7 on 2024-08-10 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_rename_product_stock_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Product'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['-create_time'], 'verbose_name': 'Stock', 'verbose_name_plural': 'Stock'},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='tag',
            new_name='type',
        ),
        migrations.AlterModelTable(
            name='product',
            table='product',
        ),
        migrations.AlterModelTable(
            name='stock',
            table='stock',
        ),
    ]
