# Generated by Django 5.0.7 on 2024-09-20 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_product_options_alter_stock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_type',
            field=models.CharField(max_length=15),
        ),
    ]
