FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN rm -rf node_modules package-lock.json

# Install dependencies
RUN npm install --force

COPY . .

RUN npm run build

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
