# Generated by Django 5.0.7 on 2024-08-08 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('SL', 'Silver'), ('GD', 'Gold'), ('PL', 'Platinum'), ('DM', 'Diamond')], default='SL', max_length=2)),
                ('points', models.IntegerField(default=0)),
                ('credit', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customer',
                'db_table': 'customer',
                'ordering': ['name'],
            },
        ),
    ]
