# Generated by Django 5.0.7 on 2024-08-09 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customer_phone'),
        ('order', '0004_remove_order_customer_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order'),
        ),
    ]
