# Generated by Django 5.0.7 on 2024-08-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='method',
            field=models.CharField(choices=[('AL', 'AliPay'), ('WE', 'WeChat'), ('CC', 'Credit Card'), ('CA', 'Cash'), ('CR', 'Credit')], max_length=2),
        ),
    ]
