# Generated by Django 5.0.7 on 2024-09-22 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='stock_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
