# Generated by Django 5.0.7 on 2024-09-22 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderitem_stock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('P', 'Paid'), ('R', 'Refund'), ('U', 'Unpaid')], default='P', max_length=1),
        ),
    ]
