# Generated by Django 5.0.7 on 2024-09-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
